services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-default-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - symfony-default
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: symfony-default-webserver
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - symfony-default
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony-default-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: symfony_api
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: symfony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - symfony-default

networks:
  symfony-default:
    driver: bridge

volumes:
  dbdata:
    driver: local
