services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-default-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-default
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: laravel-default-webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-default
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-default-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel_api
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-default

  redis:
    image: redis:alpine
    container_name: laravel-default-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - laravel-default

networks:
  laravel-default:
    driver: bridge

volumes:
  dbdata:
    driver: local
