services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-laravel-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ../../generated:/var/generated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lumen-laravel
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: lumen-laravel-webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ../../generated:/var/generated
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - lumen-laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: lumen-laravel-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: lumen_laravel_api
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: lumen_laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - lumen_dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lumen-laravel

  redis:
    image: redis:alpine
    container_name: lumen-laravel-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - lumen-laravel

networks:
  lumen-laravel:
    driver: bridge

volumes:
  lumen_dbdata:
    driver: local